version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: lxghtless/node-lerna:1.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm i
      - run: lerna init
      - run: lerna bootstrap --hoist
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - when: 
          - condition: "${CIRCLE_BRANCH}" == "master"
          - steps:
            - store_artifacts:
                path: coverage
            - codecov/upload:
                file: coverage/lcov.info
