version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: lxghtless/node-lerna:1.1.0

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm i
      - run: lerna init
      - run: lerna bootstrap --hoist
      # run build on all packages that have a build command
      - run: lerna run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - coverage
            - packages
  upload-codecov:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - codecov/upload:
          file: coverage/lcov.info
          flags: 'unittests'

workflows:
  build-test-codecov:
    jobs:
      - build
      - upload-codecov:
          requires:
            - build
          filters:
            branches:
              only: master
